# Obtener todos los medicos
GET http://localhost:3000/medicos
###

# Obtener un medico por ID (cambia el id según tus datos)
GET http://localhost:3000/medicos/109
###

# Crear un nuevo medico
POST http://localhost:3000/medicos
Content-Type: application/json

{
    "med_nombres": "Carlos Eduardo",
    "med_apellidos": "Martinez 🗿",
    "med_licencia": "LIC89658"
}
###

# Actualizar un medico (cambia el id según tus datos)
PUT http://localhost:3000/medicos/109
Content-Type: application/json

{
    "med_nombres": "Carlos Eduardin 🗿",
    "med_apellidos": "Martinez 🗿",
    "med_licencia": "LIC89658"
}
###

# Eliminar un medico (cambia el id según tus datos)
DELETE http://localhost:3000/medicos/110
